#+title: tlon-dict: Dictionary-related functions
#+author: Pablo Stafforini
#+email: pablo@stafforini.com
#+language: en
#+options: ':t toc:t author:t email:t num:t
#+startup: content
#+export_file_name: tlon-dict.info
#+texinfo_filename: tlon-dict.info
#+texinfo_dir_category: Emacs misc features
#+texinfo_dir_title: Dict: (tlon-dict)
#+texinfo_dir_desc: Dictionary-related functions

This manual describes the features and customization options for the Emacs Lisp file =tlon-dict.el=.

* Overview
:PROPERTIES:
:CUSTOM_ID: h:overview
:END:

This module integrates with the external =reverso= package to provide dictionary-related features, specifically fetching synonyms. It ensures that the language context always matches the language of the current file, as determined by Tlon's language detection, rather than relying on the default language selection mechanism of =reverso.el=.

* Commands
:PROPERTIES:
:CUSTOM_ID: h:commands
:END:

** ~tlon-reverso-get-synonyms~
:PROPERTIES:
:CUSTOM_ID: h:tlon-reverso-get-synonyms
:END:
#+findex: tlon-reverso-get-synonyms

Fetch synonyms for a word using the =reverso.el= package. The command determines the language of the current file using ~tlon-get-language-in-file~ and looks up the corresponding language name recognized by Reverso via Tlon's configuration (~tlon-lookup~). If the language cannot be determined, the command signals an error.

You are prompted for the word to look up, defaulting to the word at point (~thing-at-point 'word~). The results are displayed in a dedicated Reverso buffer, as with the standard =reverso.el= workflow.

* Transient menu
:PROPERTIES:
:CUSTOM_ID: h:menu
:END:
#+findex: tlon-dict-menu

The command ~tlon-dict-menu~ activates a =transient= menu interface for dictionary-related commands. It provides:

- =s= :: Synonyms (~tlon-reverso-get-synonyms~)

* Indices
:PROPERTIES:
:CUSTOM_ID: h:indices
:END:

** Function index
:PROPERTIES:
:INDEX: fn
:CUSTOM_ID: h:function-index
:END:

** Variable index
:PROPERTIES:
:INDEX: vr
:CUSTOM_ID: h:variable-index
:END:
